<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../includes/business_profile.php';
require_once __DIR__ . '/../includes/location.php';

$user = require_login('BUSINESS');
$existing = business_profile((int) $user['id']);
$fields = ['business_name' => '', 'owner_name' => $user['full_name'], 'business_email' => $user['email'], 'business_phone' => $user['phone'], 'business_category' => '', 'business_address' => '', 'city' => '', 'state' => '', 'country' => '', 'pincode' => '', 'business_description' => '', 'website' => '', 'gst_number' => ''];
$values = array_merge($fields, $existing ?: []);
$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        verify_csrf();
        foreach ($fields as $field => $default) $values[$field] = trim((string) ($_POST[$field] ?? $default));
        if (mb_strlen($values['business_name']) < 2 || mb_strlen($values['business_name']) > 150) $errors['business_name'] = 'Enter a business name between 2 and 150 characters.';
        if (mb_strlen($values['owner_name']) < 2 || mb_strlen($values['owner_name']) > 100) $errors['owner_name'] = 'Enter an owner name between 2 and 100 characters.';
        if (!filter_var($values['business_email'], FILTER_VALIDATE_EMAIL) || mb_strlen($values['business_email']) > 150) $errors['business_email'] = 'Enter a valid business email address.';
        if (!preg_match('/^[0-9+() .-]{7,25}$/', $values['business_phone'])) $errors['business_phone'] = 'Enter a valid business phone number.';
        if ($values['business_category'] === '' || $values['business_category'] === 'Other' || mb_strlen($values['business_category']) > 100) $errors['business_category'] = 'Choose or enter a business category of up to 100 characters.';
        foreach (['business_address' => 255, 'city' => 100, 'state' => 100, 'country' => 100, 'pincode' => 20] as $field => $limit) if ($values[$field] === '' || mb_strlen($values[$field]) > $limit) $errors[$field] = 'This field is required.';
        if (mb_strlen($values['business_description']) < 20 || mb_strlen($values['business_description']) > 3000) $errors['business_description'] = 'Use 20 to 3,000 characters to describe your business.';
        if ($values['website'] !== '' && (!filter_var($values['website'], FILTER_VALIDATE_URL) || !in_array(parse_url($values['website'], PHP_URL_SCHEME), ['http', 'https'], true))) $errors['website'] = 'Use a valid http:// or https:// website URL.';
        if ($values['gst_number'] !== '' && !preg_match('/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/', strtoupper($values['gst_number']))) $errors['gst_number'] = 'Enter a valid 15-character GST number.';
        if ($errors) throw new RuntimeException('Please correct the highlighted fields.');

        $logo = business_upload($_FILES['logo'] ?? [], 'logo') ?: ($existing['logo'] ?? null);
        $document = business_upload($_FILES['verification_document'] ?? [], 'document') ?: ($existing['verification_document'] ?? null);
        if (!$logo) $errors['logo'] = 'A business logo is required.';
        if (!$document) $errors['verification_document'] = 'A verification document is required.';
        if ($errors) throw new RuntimeException('Please add the required uploads.');
        $complete = 1;
        $data = [$values['business_name'], $values['owner_name'], $values['business_email'], $values['business_phone'], $values['business_category'], $values['business_address'], $values['city'], $values['state'], $values['country'], $values['pincode'], $values['business_description'], $values['website'] ?: null, strtoupper($values['gst_number']) ?: null, $logo, $document, $complete, $user['id']];
        if ($existing) {
            $sql = 'UPDATE business_profiles SET business_name=?, owner_name=?, business_email=?, business_phone=?, business_category=?, business_address=?, city=?, state=?, country=?, pincode=?, business_description=?, website=?, gst_number=?, logo=?, verification_document=?, is_profile_completed=? WHERE user_id=?';
        } else {
            $sql = 'INSERT INTO business_profiles (business_name, owner_name, business_email, business_phone, business_category, business_address, city, state, country, pincode, business_description, website, gst_number, logo, verification_document, is_profile_completed, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
        }
        db()->prepare($sql)->execute($data);
        ActivityLogService::logActivity((int) $user['id'], 'BUSINESS', 'Business', 'Business Profile Update', 'BusinessProfile', (int) $user['id'], $existing ? 'Business profile updated.' : 'Business profile completed.');
        set_flash('success', $existing ? 'Business profile updated successfully.' : 'Business profile completed successfully.');
        redirect('business/dashboard.php');
    } catch (Throwable $exception) {
        app_log('Business profile update failed: ' . $exception->getMessage());
        $errors['general'] = $exception instanceof RuntimeException ? $exception->getMessage() : 'We could not save your profile. Please try again.';
    }
}
$pageTitle = ($existing ? 'Edit' : 'Complete') . ' business profile | ' . APP_NAME;
require_once __DIR__ . '/../includes/header.php';
?>
<main class="profile-page"><div class="container py-5"><div class="profile-hero"><div><span class="eyebrow"><i class="bi bi-building-check"></i> Business profile</span><h1><?= $existing ? 'Keep your profile current.' : 'Set up your business profile.' ?></h1><p>Share the essentials once, then unlock your business workspace.</p></div><a href="<?= e(url('business/dashboard.php')) ?>" class="btn btn-light border">Back to dashboard</a></div>
<?php if (isset($errors['general'])): ?><div class="alert alert-danger mt-4"><?= e($errors['general']) ?></div><?php endif; ?>
<form method="post" enctype="multipart/form-data" class="profile-wizard needs-validation mt-4" novalidate><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="wizard-progress"><span class="active">1</span><span>2</span><span>3</span><span>4</span><span>5</span></div>
<section class="wizard-step active" data-step="1"><div class="wizard-heading"><span>Step 1 of 5</span><h2>Business information</h2><p>Tell us who we are verifying.</p></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="business_name">Business name</label><input id="business_name" class="form-control" name="business_name" required maxlength="150" value="<?= e($values['business_name']) ?>"><div class="invalid-feedback"><?= e($errors['business_name'] ?? 'Business name is required.') ?></div></div><div class="col-md-6"><label class="form-label" for="owner_name">Owner name</label><input id="owner_name" class="form-control" name="owner_name" required maxlength="100" value="<?= e($values['owner_name']) ?>"><div class="invalid-feedback"><?= e($errors['owner_name'] ?? 'Owner name is required.') ?></div></div><div class="col-md-6"><label class="form-label" for="business_email">Business email</label><input id="business_email" type="email" class="form-control" name="business_email" required maxlength="150" value="<?= e($values['business_email']) ?>"><div class="invalid-feedback"><?= e($errors['business_email'] ?? 'A valid email is required.') ?></div></div><div class="col-md-6"><label class="form-label" for="business_phone">Business phone</label><input id="business_phone" type="tel" class="form-control" name="business_phone" required maxlength="25" value="<?= e($values['business_phone']) ?>"><div class="invalid-feedback"><?= e($errors['business_phone'] ?? 'A valid phone number is required.') ?></div></div></div></section>
<section class="wizard-step" data-step="2"><div class="wizard-heading"><span>Step 2 of 5</span><h2>Choose your category</h2><p class="required-label">Search a suggested category or type your own.</p></div><label class="form-label" for="business_category">Business category</label><div class="category-control"><i class="bi bi-search" aria-hidden="true"></i><input id="business_category" class="form-control" name="business_category" list="business-category-options" required maxlength="100" autocomplete="off" placeholder="Search or enter a category" value="<?= e($values['business_category']) ?>" data-category-control><i class="bi bi-chevron-down" aria-hidden="true"></i></div><datalist id="business-category-options"><?php foreach (BUSINESS_PROFILE_CATEGORIES as $category): ?><option value="<?= e($category) ?>"></option><?php endforeach; ?></datalist><p class="form-text mb-0">Choose <strong>Other</strong> to clear this field and enter a custom category.</p><?php if (isset($errors['business_category'])): ?><p class="text-danger small mt-3 mb-0"><?= e($errors['business_category']) ?></p><?php endif; ?></section>
<section class="wizard-step" data-step="3"><div class="wizard-heading"><span>Step 3 of 5</span><h2>Business address</h2><p>Where does your business operate from?</p></div><div class="row g-3"><div class="col-12"><label class="form-label" for="business_address">Address / House No. / Building Name</label><input id="business_address" class="form-control" name="business_address" required maxlength="255" value="<?= e($values['business_address']) ?>"></div><div class="col-md-6"><label class="form-label" for="pincode">PIN Code</label><div class="position-relative"><input id="pincode" class="form-control" name="pincode" required maxlength="6" inputmode="numeric" pattern="\d{6}" placeholder="Enter 6-digit PIN Code" value="<?= e($values['pincode']) ?>" data-pincode-lookup><span class="pincode-spinner position-absolute top-50 end-0 translate-middle-y me-3" hidden><span class="spinner-border spinner-border-sm text-primary" role="status"><span class="visually-hidden">Loading...</span></span></span><div class="pincode-feedback small mt-1" hidden></div></div></div><div class="col-md-6"><label class="form-label" for="city">City</label><input id="city" class="form-control" name="city" required maxlength="100" value="<?= e($values['city']) ?>" data-pincode-city></div><div class="col-md-6"><label class="form-label" for="state">State</label><input id="state" class="form-control" name="state" required maxlength="100" value="<?= e($values['state']) ?>" data-pincode-state></div><div class="col-md-6"><label class="form-label" for="country">Country</label><input id="country" class="form-control" name="country" required maxlength="100" value="<?= e($values['country'] ?: 'India') ?>" readonly data-pincode-country></div></div></section>
<section class="wizard-step" data-step="4"><div class="wizard-heading"><span>Step 4 of 5</span><h2>Business details</h2><p>A little more context helps build confidence.</p></div><div class="row g-3"><div class="col-12"><label class="form-label">Business description</label><textarea class="form-control" name="business_description" required minlength="20" maxlength="3000" rows="6"><?= e($values['business_description']) ?></textarea><div class="invalid-feedback"><?= e($errors['business_description'] ?? 'Describe your business in at least 20 characters.') ?></div></div><div class="col-md-6"><label class="form-label">Website <small>(optional)</small></label><input type="url" class="form-control" name="website" maxlength="255" placeholder="https://example.com" value="<?= e($values['website']) ?>"></div><div class="col-md-6"><label class="form-label">GST number <small>(optional)</small></label><input class="form-control text-uppercase" name="gst_number" maxlength="15" value="<?= e($values['gst_number']) ?>"></div></div></section>
<section class="wizard-step" data-step="5"><div class="wizard-heading"><span>Step 5 of 5</span><h2>Uploads and review</h2><p>Your files are used only for business verification.</p></div><div class="row g-4"><div class="col-md-6"><label class="upload-card"><input type="file" name="logo" accept="image/png,image/jpeg" <?= $existing && $existing['logo'] ? '' : 'required' ?> data-preview="logo-preview"><i class="bi bi-image"></i><strong>Business logo</strong><small>PNG, JPG, or JPEG · up to 2 MB</small><?php if ($existing && $existing['logo']): ?><img id="logo-preview" src="<?= e(url($existing['logo'])) ?>" alt="Current business logo"><?php else: ?><img id="logo-preview" alt="Logo preview" hidden><?php endif; ?></label><?php if (isset($errors['logo'])): ?><p class="text-danger small mt-2"><?= e($errors['logo']) ?></p><?php endif; ?></div><div class="col-md-6"><label class="upload-card"><input type="file" name="verification_document" accept="image/png,image/jpeg,application/pdf" <?= $existing && $existing['verification_document'] ? '' : 'required' ?>><i class="bi bi-file-earmark-check"></i><strong>Verification document</strong><small>PNG, JPG, JPEG, or PDF · up to 5 MB</small><?php if ($existing && $existing['verification_document']): ?><em>Document already uploaded</em><?php endif; ?></label><?php if (isset($errors['verification_document'])): ?><p class="text-danger small mt-2"><?= e($errors['verification_document']) ?></p><?php endif; ?></div></div></section>
<div class="wizard-actions" data-wizard-actions><button type="button" class="btn btn-light border wizard-back" hidden><i class="bi bi-arrow-left"></i> Back</button><button type="button" class="btn btn-primary wizard-next">Continue <i class="bi bi-arrow-right"></i></button><button type="submit" class="btn btn-primary wizard-submit" hidden>Save business profile <i class="bi bi-check2-circle"></i></button></div></form></div></main>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
