<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/app.php'; require_once __DIR__ . '/../includes/customer_referrals.php'; require_once __DIR__ . '/../includes/referral_opportunities.php';
$user = require_login('BUSINESS'); $businessId = (int) $user['id'];
$search = mb_substr(trim((string) ($_GET['search'] ?? '')), 0, 100); $campaignId = filter_var($_GET['campaign_id'] ?? null, FILTER_VALIDATE_INT, ['options'=>['min_range'=>1]]) ?: null; $product = mb_substr(trim((string) ($_GET['product'] ?? '')), 0, 150); $status = in_array($_GET['status'] ?? '', CUSTOMER_REFERRAL_STATUSES, true) ? (string) $_GET['status'] : '';
$dateFrom = trim((string) ($_GET['date_from'] ?? '')); $dateTo = trim((string) ($_GET['date_to'] ?? '')); foreach (['dateFrom','dateTo'] as $field) { $date = DateTimeImmutable::createFromFormat('!Y-m-d', $$field); if (!$date || $date->format('Y-m-d') !== $$field) $$field = ''; }
$sort = in_array($_GET['sort'] ?? '', ['newest','oldest','commission_high','commission_low'], true) ? (string) $_GET['sort'] : 'newest'; $order = ['newest'=>'r.submitted_at DESC, r.id DESC','oldest'=>'r.submitted_at ASC, r.id ASC','commission_high'=>'COALESCE(r.calculated_commission, r.reward_amount) DESC, r.submitted_at DESC','commission_low'=>'COALESCE(r.calculated_commission, r.reward_amount) ASC, r.submitted_at DESC'][$sort];
$where=['r.business_id = ?']; $params=[$businessId];
if ($search !== '') { $where[]='(CAST(r.id AS CHAR) LIKE ? OR r.customer_name LIKE ? OR r.customer_phone LIKE ? OR r.product_name LIKE ?)'; foreach (range(1,4) as $_) $params[]='%'.$search.'%'; }
if ($campaignId) { $where[]='r.opportunity_id = ?'; $params[]=$campaignId; } if ($product !== '') { $where[]='r.product_name = ?'; $params[]=$product; } if ($status !== '') { $where[]='r.status = ?'; $params[]=$status; } if ($dateFrom !== '') { $where[]='r.submitted_at >= ?'; $params[]=$dateFrom.' 00:00:00'; } if ($dateTo !== '') { $where[]='r.submitted_at < DATE_ADD(?, INTERVAL 1 DAY)'; $params[]=$dateTo; }
$whereSql=implode(' AND ', $where); $count=db()->prepare("SELECT COUNT(*) FROM customer_referrals r WHERE {$whereSql}"); $count->execute($params); $total=(int)$count->fetchColumn(); $perPage=20; $page=max(1,(int)($_GET['page']??1)); $page=min($page,max(1,(int)ceil($total/$perPage)));
$statement=db()->prepare("SELECT r.*, o.title AS opportunity_title, u.full_name AS referrer_name FROM customer_referrals r JOIN referral_opportunities o ON o.id=r.opportunity_id JOIN users u ON u.id=r.referrer_id WHERE {$whereSql} ORDER BY {$order} LIMIT {$perPage} OFFSET ".(($page-1)*$perPage)); $statement->execute($params); $referrals=$statement->fetchAll();
$campaigns=db()->prepare('SELECT id,title FROM referral_opportunities WHERE business_id=? ORDER BY title'); $campaigns->execute([$businessId]); $products=db()->prepare("SELECT DISTINCT product_name FROM customer_referrals WHERE business_id=? AND product_name IS NOT NULL AND product_name<>'' ORDER BY product_name"); $products->execute([$businessId]);
$query=static function(array $changes=[]) use($search,$campaignId,$product,$status,$dateFrom,$dateTo,$sort): string { return http_build_query(array_filter(array_merge(['search'=>$search,'campaign_id'=>$campaignId,'product'=>$product,'status'=>$status,'date_from'=>$dateFrom,'date_to'=>$dateTo,'sort'=>$sort],$changes),static fn($v)=>$v!==''&&$v!==null)); }; $pageTitle='Customer referrals | '.APP_NAME; require_once __DIR__.'/../includes/header.php';
?>
<main class="opportunity-page"><div class="container py-5"><div class="opportunity-hero"><div><span class="eyebrow"><i class="bi bi-people"></i> Business workspace</span><h1>Customer referrals</h1><p>Find, review, and sort every customer introduction.</p></div><a class="btn btn-light border" href="<?=e(url('business/dashboard.php'))?>">Back to dashboard</a></div><section class="opportunity-list-card mt-4"><div class="list-card-heading"><div><h2>Referrals</h2><p><?= $total ?> result<?= $total===1?'':'s' ?> found</p></div></div><form method="get" class="row g-3 filter-panel"><div class="col-lg-4"><input class="form-control" name="search" value="<?=e($search)?>" placeholder="ID, customer, phone, or product" data-instant-search></div><div class="col-sm-6 col-lg-2"><select class="form-select" name="campaign_id"><option value="">All campaigns</option><?php foreach($campaigns->fetchAll() as $campaign):?><option value="<?= (int)$campaign['id']?>" <?= $campaignId===(int)$campaign['id']?'selected':''?>><?=e($campaign['title'])?></option><?php endforeach;?></select></div><div class="col-sm-6 col-lg-2"><select class="form-select" name="product"><option value="">All products</option><?php foreach($products->fetchAll(PDO::FETCH_COLUMN) as $item):?><option <?= $product===$item?'selected':''?>><?=e($item)?></option><?php endforeach;?></select></div><div class="col-sm-4 col-lg-2"><select class="form-select" name="status"><option value="">All statuses</option><?php foreach(CUSTOMER_REFERRAL_STATUSES as $item):?><option <?= $status===$item?'selected':''?>><?=e($item)?></option><?php endforeach;?></select></div><div class="col-sm-4 col-lg-2"><select class="form-select" name="sort"><option value="newest" <?=$sort==='newest'?'selected':''?>>Newest</option><option value="oldest" <?=$sort==='oldest'?'selected':''?>>Oldest</option><option value="commission_high" <?=$sort==='commission_high'?'selected':''?>>Highest commission</option><option value="commission_low" <?=$sort==='commission_low'?'selected':''?>>Lowest commission</option></select></div><div class="col-sm-4 col-lg-3"><input class="form-control" type="date" name="date_from" value="<?=e($dateFrom)?>" aria-label="From date"></div><div class="col-sm-4 col-lg-3"><input class="form-control" type="date" name="date_to" value="<?=e($dateTo)?>" aria-label="To date"></div><div class="col-sm-4 col-lg-6 d-flex gap-2"><button class="btn btn-outline-primary">Apply filters</button><a class="btn btn-light border" href="<?=e(url('business/referrals.php'))?>">Clear filters</a></div></form>
<?php if(!$referrals):?><div class="empty-state"><span><i class="bi bi-person-plus"></i></span><h3>No referrals found</h3><p>Try clearing or adjusting the filters.</p></div><?php else:?><div class="table-responsive"><table class="table opportunity-table align-middle"><thead><tr><th>Referral</th><th>Customer</th><th>Product</th><th>Campaign</th><th>Commission</th><th>Sale / Commission</th><th>Status</th><th>Submitted</th><th class="text-end">Action</th></tr></thead><tbody><?php foreach($referrals as $referral):?><tr><td>#<?= (int)$referral['id']?></td><td><strong><?=e($referral['customer_name'])?></strong><small><?=e($referral['customer_phone'])?> · <?=e($referral['referrer_name'])?></small></td><td><?=e($referral['product_name']?:'Legacy referral')?></td><td><?=e($referral['opportunity_title'])?></td><td><?=$referral['commission_percentage']!==null?e($referral['commission_percentage']).'%':'—'?></td><td><?=$referral['status']==='Completed'?e(opportunity_money($referral['sale_amount'])).' / '.e(opportunity_money($referral['calculated_commission'])):'Pending'?></td><td><span class="role-badge"><?=e($referral['status'])?></span></td><td><?=e(date('d M Y',strtotime($referral['submitted_at'])))?></td><td class="text-end"><a class="btn btn-sm btn-light border" href="<?=e(url('business/referral_view.php?id='.$referral['id']))?>"><?= $referral['status']==='Completed'?'View':'Review'?></a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><?php if($total>$perPage):?><nav class="mt-3"><ul class="pagination justify-content-end mb-0"><?php for($p=1;$p<=ceil($total/$perPage);$p++):?><li class="page-item <?=$p===$page?'active':''?>"><a class="page-link" href="<?=e(url('business/referrals.php?'.$query(['page'=>$p])))?>"><?=$p?></a></li><?php endfor;?></ul></nav><?php endif;?></section></div></main>
<?php require_once __DIR__.'/../includes/footer.php'; ?>
