<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../includes/business_profile.php';
require_once __DIR__ . '/../includes/customer_referrals.php';
require_once __DIR__ . '/../includes/referral_opportunities.php';
require_once __DIR__ . '/../includes/reports.php';
$user = require_login('BUSINESS', true);
if (!business_profile_is_complete((int) $user['id'])) { set_flash('warning', 'Complete your business profile before opening reports.'); redirect('business/profile.php'); }
$businessId = (int) $user['id']; $type = in_array($_GET['type'] ?? '', BUSINESS_REPORT_TYPES, true) ? (string) $_GET['type'] : 'referrals'; $filters = report_filters($_GET);
$sort = (string) ($_GET['sort'] ?? 'submitted_at'); $direction = strtolower((string) ($_GET['dir'] ?? 'desc')) === 'asc' ? 'asc' : 'desc'; $page = max(1, (int) ($_GET['page'] ?? 1)); $perPage = 20;
try {
    $options = report_options($businessId); $summary = report_earnings_summary($businessId, $filters); $charts = report_chart_data($businessId, $filters);
    $total = $type === 'referrals' ? report_referral_count($businessId, $filters) : 0;
    $rows = match ($type) { 'commissions' => report_commissions($businessId, $filters), 'campaigns' => report_campaign_performance($businessId, $filters), 'earnings' => [], default => report_referrals($businessId, $filters, $sort, $direction, $perPage, ($page - 1) * $perPage) };
} catch (Throwable $exception) { app_log('Business reports failed: ' . $exception->getMessage()); $options = ['campaigns' => [], 'products' => [], 'referrers' => []]; $summary = []; $charts = ['monthly_referrals'=>[], 'monthly_commission'=>[], 'campaign_performance'=>[], 'status_distribution'=>[]]; $rows = []; $total = 0; set_flash('danger', 'Report data could not be loaded. Please try again.'); }
$query = static function (array $changes = []) use ($type, $filters, $sort, $direction): string { return http_build_query(array_filter(array_merge(['type'=>$type, 'sort'=>$sort, 'dir'=>$direction], $filters, $changes), static fn($value) => $value !== '' && $value !== null && $value !== false)); };
$sortUrl = static function (string $column) use ($query, $sort, $direction): string { return url('business/reports.php?' . $query(['sort'=>$column, 'dir'=> $sort === $column && $direction === 'asc' ? 'desc' : 'asc', 'page'=>1])); };
$pageTitle = 'Business Reports | ' . APP_NAME; require_once __DIR__ . '/../includes/header.php';
?>
<main class="dashboard-page reports-page"><div class="container py-5">
<section class="dashboard-welcome business-welcome"><div><span class="eyebrow"><i class="bi bi-clipboard-data"></i> Module 8</span><h1>Reports &amp; Exports</h1><p>Track referral outcomes, commissions, campaign performance, and earnings in one place.</p></div><a class="btn btn-light border" href="<?= e(url('business/dashboard.php')) ?>">Back to dashboard</a></section>
<div class="report-tabs mt-4"><?php foreach (['referrals'=>['Referral Report','bi-person-lines-fill'], 'commissions'=>['Commission Report','bi-cash-coin'], 'campaigns'=>['Campaign Performance','bi-graph-up-arrow'], 'earnings'=>['Earnings Summary','bi-wallet2']] as $key => [$label,$icon]): ?><a class="<?= $type === $key ? 'active' : '' ?>" href="<?= e(url('business/reports.php?' . $query(['type'=>$key, 'page'=>1]))) ?>"><i class="bi <?= e($icon) ?>"></i><?= e($label) ?></a><?php endforeach; ?></div>
<section class="dashboard-panel mt-4 report-filter-panel"><div class="panel-heading"><div><h2>Filter report</h2><p>Filters apply to the table, KPIs, charts, and exported file.</p></div></div><form method="get" class="row g-3"><input type="hidden" name="type" value="<?= e($type) ?>"><div class="col-sm-6 col-lg-2"><label class="form-label" for="date_from">From</label><input class="form-control" id="date_from" type="date" name="date_from" value="<?= e($filters['date_from']) ?>"></div><div class="col-sm-6 col-lg-2"><label class="form-label" for="date_to">To</label><input class="form-control" id="date_to" type="date" name="date_to" value="<?= e($filters['date_to']) ?>"></div><div class="col-sm-6 col-lg-2"><label class="form-label" for="campaign_id">Campaign</label><select class="form-select" id="campaign_id" name="campaign_id"><option value="">All campaigns</option><?php foreach ($options['campaigns'] as $campaign): ?><option value="<?= (int) $campaign['id'] ?>" <?= $filters['campaign_id'] === (int) $campaign['id'] ? 'selected' : '' ?>><?= e($campaign['title']) ?></option><?php endforeach; ?></select></div><div class="col-sm-6 col-lg-2"><label class="form-label" for="product">Product</label><select class="form-select" id="product" name="product"><option value="">All products</option><?php foreach ($options['products'] as $product): ?><option <?= $filters['product'] === $product ? 'selected' : '' ?>><?= e($product) ?></option><?php endforeach; ?></select></div><div class="col-sm-6 col-lg-2"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">All statuses</option><?php foreach (CUSTOMER_REFERRAL_STATUSES as $status): ?><option <?= $filters['status'] === $status ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select></div><div class="col-sm-6 col-lg-2"><label class="form-label" for="referrer_id">Referrer</label><select class="form-select" id="referrer_id" name="referrer_id"><option value="">All referrers</option><?php foreach ($options['referrers'] as $referrer): ?><option value="<?= (int) $referrer['id'] ?>" <?= $filters['referrer_id'] === (int) $referrer['id'] ? 'selected' : '' ?>><?= e($referrer['full_name']) ?></option><?php endforeach; ?></select></div><div class="col-lg-9"><label class="form-label" for="search">Search</label><input class="form-control" id="search" name="search" maxlength="100" placeholder="Customer, product, campaign or referrer" value="<?= e($filters['search']) ?>"></div><div class="col-lg-3 d-flex align-items-end gap-2"><button class="btn btn-primary flex-grow-1"><i class="bi bi-funnel"></i> Apply</button><a class="btn btn-light border" href="<?= e(url('business/reports.php?type=' . $type)) ?>">Reset</a></div></form></section>
<section class="row g-3 mt-1"><?php foreach ([['Total Revenue','total_revenue','bi-receipt'],['Gross Commission','total_commission_paid','bi-cash-stack'],['Platform Fees (2%)','total_platform_fees','bi-percent'],['Net Commission Paid','total_net_commission','bi-cash-coin'],['Completed Referrals','completed_referrals','bi-award'],['Pending Referrals','pending_referrals','bi-hourglass-split']] as [$label,$field,$icon]): ?><div class="col-6 col-lg"><article class="report-kpi"><i class="bi <?= e($icon) ?>"></i><span><?= e($label) ?></span><strong><?= in_array($field, ['total_revenue','total_commission_paid','total_platform_fees','total_net_commission'], true) ? e(opportunity_money($summary[$field] ?? 0)) : (int) ($summary[$field] ?? 0) ?></strong></article></div><?php endforeach; ?></section>
<section class="dashboard-panel mt-4"><div class="panel-heading"><div><h2><?= e(['referrals'=>'Referral Report','commissions'=>'Commission Report','campaigns'=>'Campaign Performance Report','earnings'=>'Earnings Summary Report'][$type]) ?></h2><p><?= $type === 'earnings' ? 'A concise view of filtered business earnings.' : 'Use the filters and export the matching data when needed.' ?></p></div><div class="report-export"><a class="btn btn-sm btn-outline-primary" href="<?= e(url('business/report_export.php?' . $query(['format'=>'csv']))) ?>">CSV</a><a class="btn btn-sm btn-outline-primary" href="<?= e(url('business/report_export.php?' . $query(['format'=>'xlsx']))) ?>">Excel</a><a class="btn btn-sm btn-primary" href="<?= e(url('business/report_export.php?' . $query(['format'=>'pdf']))) ?>">PDF</a></div></div>
<?php if ($type === 'earnings'): ?><div class="table-responsive"><table class="table opportunity-table"><tbody><?php foreach (report_export_rows($businessId, $filters, 'earnings') as $row): ?><tr><th><?= e($row['metric']) ?></th><td><?= in_array($row['metric'], ['Total Revenue','Total Gross Commission','Total Platform Fees (2%)','Total Net Commission Paid'], true) ? e(opportunity_money($row['value'])) : (int) $row['value'] ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif ($type === 'campaigns'): ?><div class="table-responsive"><table class="table opportunity-table"><thead><tr><th>Campaign Name</th><th>Total</th><th>Accepted</th><th>Rejected</th><th>Completed</th><th>Conversion</th><th>Revenue</th><th>Gross Commission</th><th>Platform Fees</th><th>Net Commission</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><strong><?= e($row['campaign_name']) ?></strong></td><td><?= (int) $row['total_referrals'] ?></td><td><?= (int) $row['accepted_referrals'] ?></td><td><?= (int) $row['rejected_referrals'] ?></td><td><?= (int) $row['completed_referrals'] ?></td><td><?= e((string) $row['conversion_rate']) ?>%</td><td><?= e(opportunity_money($row['total_revenue'])) ?></td><td><?= e(opportunity_money($row['total_commission_paid'])) ?></td><td><?= e(opportunity_money($row['total_platform_fees'])) ?></td><td><?= e(opportunity_money($row['total_net_commission'])) ?></td></tr><?php endforeach; if (!$rows): ?><tr><td colspan="10" class="text-center text-muted py-4">No campaign performance data matches these filters.</td></tr><?php endif; ?></tbody></table></div>
<?php elseif ($type === 'commissions'): ?><div class="table-responsive"><table class="table opportunity-table"><thead><tr><th>Referrer</th><th>Product</th><th>Campaign</th><th>Sale Amount</th><th>Commission %</th><th>Gross Commission</th><th>Platform Fee</th><th>Net Commission</th><th>Completion Date</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><?= e($row['referrer_name']) ?></td><td><?= e($row['product_name'] ?: 'Legacy referral') ?></td><td><?= e($row['campaign_name']) ?></td><td><?= e(opportunity_money($row['sale_amount'])) ?></td><td><?= e((string) $row['commission_percentage']) ?>%</td><td><?= e(opportunity_money($row['calculated_commission'])) ?></td><td><?= e(opportunity_money($row['platform_fee'] ?? 0)) ?></td><td><?= e(opportunity_money($row['net_commission'] ?? $row['calculated_commission'])) ?></td><td><?= e(date('d M Y', strtotime($row['completed_at']))) ?></td></tr><?php endforeach; if (!$rows): ?><tr><td colspan="9" class="text-center text-muted py-4">No completed commission records match these filters.</td></tr><?php endif; ?></tbody></table></div>
<?php else: ?><div class="table-responsive"><table class="table opportunity-table report-table"><thead><tr><?php foreach (['id'=>'Referral ID','customer_name'=>'Customer','product'=>'Product','campaign'=>'Campaign','status'=>'Status','referrer'=>'Referrer','sale_amount'=>'Sale Amount','commission'=>'Commission','submitted_at'=>'Submitted','completed_at'=>'Completed'] as $column=>$label): ?><th><a href="<?= e($sortUrl($column)) ?>"><?= e($label) ?><?= $sort === $column ? ($direction === 'asc' ? ' ↑' : ' ↓') : '' ?></a></th><?php endforeach; ?></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td>#<?= (int) $row['id'] ?></td><td><?= e($row['customer_name']) ?></td><td><?= e($row['product_name'] ?: 'Legacy referral') ?></td><td><?= e($row['campaign_name']) ?></td><td><span class="role-badge"><?= e($row['status']) ?></span></td><td><?= e($row['referrer_name']) ?></td><td><?= $row['sale_amount'] !== null ? e(opportunity_money($row['sale_amount'])) : '—' ?></td><td><?= $row['commission_percentage'] !== null ? e((string) $row['commission_percentage']) . '% / ' . e(opportunity_money($row['calculated_commission'])) : '—' ?></td><td><?= e(date('d M Y', strtotime($row['submitted_at']))) ?></td><td><?= $row['completed_at'] ? e(date('d M Y', strtotime($row['completed_at']))) : '—' ?></td></tr><?php endforeach; if (!$rows): ?><tr><td colspan="10" class="text-center text-muted py-4">No referrals match these filters.</td></tr><?php endif; ?></tbody></table></div><?php if ($total > $perPage): ?><nav class="mt-3"><ul class="pagination mb-0 justify-content-end"><?php for ($p=1; $p <= (int) ceil($total / $perPage); $p++): ?><li class="page-item <?= $p === $page ? 'active' : '' ?>"><a class="page-link" href="<?= e(url('business/reports.php?' . $query(['page'=>$p]))) ?>"><?= $p ?></a></li><?php endfor; ?></ul></nav><?php endif; ?><?php endif; ?></section>
<section class="row g-4 mt-1"><div class="col-lg-6"><div class="dashboard-panel chart-card"><h2>Monthly Referral Trend</h2><canvas id="referralTrend"></canvas></div></div><div class="col-lg-6"><div class="dashboard-panel chart-card"><h2>Monthly Commission Paid</h2><canvas id="commissionTrend"></canvas></div></div><div class="col-lg-6"><div class="dashboard-panel chart-card"><h2>Campaign Performance</h2><canvas id="campaignChart"></canvas></div></div><div class="col-lg-6"><div class="dashboard-panel chart-card"><h2>Referral Status Distribution</h2><canvas id="statusChart"></canvas></div></div></section>
</div></main>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script><script>const reportCharts=<?= json_encode($charts, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;const draw=(id,data,label,type='bar')=>new Chart(document.getElementById(id),{type,data:{labels:data.map(x=>x.label),datasets:[{label,data:data.map(x=>Number(x.value)),backgroundColor:['#2457d6','#16a085','#f39c12','#8e44ad','#e74c3c','#3498db','#2ecc71','#d35400']}]},options:{responsive:true,plugins:{legend:{display:type==='doughnut'}}}});draw('referralTrend',reportCharts.monthly_referrals,'Referrals','line');draw('commissionTrend',reportCharts.monthly_commission,'Commission paid','line');draw('campaignChart',reportCharts.campaign_performance,'Referrals');draw('statusChart',reportCharts.status_distribution,'Referrals','doughnut');</script>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
