<?php
declare(strict_types=1);
require_once __DIR__ . '/config/app.php';
$user = require_login(); $userId = (int) $user['id'];
$search = mb_substr(trim((string) ($_GET['search'] ?? '')), 0, 100); $module = mb_substr(trim((string) ($_GET['module'] ?? '')), 0, 50); $action = mb_substr(trim((string) ($_GET['action'] ?? '')), 0, 100);
$from = trim((string) ($_GET['from'] ?? '')); $to = trim((string) ($_GET['to'] ?? '')); foreach (['from', 'to'] as $dateKey) { if ($$dateKey !== '' && !preg_match('/^\d{4}-\d{2}-\d{2}$/', $$dateKey)) $$dateKey = ''; }
$where = ['user_id = ?']; $params = [$userId]; if ($search !== '') { $where[] = '(action LIKE ? OR module LIKE ? OR description LIKE ?)'; $params[] = "%{$search}%"; $params[] = "%{$search}%"; $params[] = "%{$search}%"; } if ($module !== '') { $where[] = 'module = ?'; $params[] = $module; } if ($action !== '') { $where[] = 'action = ?'; $params[] = $action; } if ($from !== '') { $where[] = 'created_at >= ?'; $params[] = $from . ' 00:00:00'; } if ($to !== '') { $where[] = 'created_at <= ?'; $params[] = $to . ' 23:59:59'; }
$whereSql = implode(' AND ', $where); $query = static function (array $changes = []) use ($search, $module, $action, $from, $to): string { return http_build_query(array_filter(array_merge(compact('search', 'module', 'action', 'from', 'to'), $changes), static fn($value) => $value !== '')); };
if (($_GET['export'] ?? '') === 'csv') { $stmt = db()->prepare("SELECT created_at, module, action, entity_type, entity_id, description, ip_address, user_agent FROM activity_logs WHERE {$whereSql} ORDER BY created_at DESC, id DESC"); $stmt->execute($params); header('Content-Type: text/csv; charset=utf-8'); header('Content-Disposition: attachment; filename=activity-log-' . date('Ymd-His') . '.csv'); $out = fopen('php://output', 'w'); fputcsv($out, ['Date', 'Module', 'Action', 'Entity type', 'Entity ID', 'Description', 'IP address', 'User agent']); foreach ($stmt as $row) fputcsv($out, $row); fclose($out); exit; }
$options = db()->prepare('SELECT DISTINCT module, action FROM activity_logs WHERE user_id = ? ORDER BY module, action'); $options->execute([$userId]); $optionRows = $options->fetchAll(); $modules = array_values(array_unique(array_column($optionRows, 'module'))); $actions = array_values(array_unique(array_column($optionRows, 'action')));
$count = db()->prepare("SELECT COUNT(*) FROM activity_logs WHERE {$whereSql}"); $count->execute($params); $total = (int) $count->fetchColumn(); $perPage = 25; $page = min(max(1, (int) ($_GET['page'] ?? 1)), max(1, (int) ceil($total / $perPage))); $stmt = db()->prepare("SELECT * FROM activity_logs WHERE {$whereSql} ORDER BY created_at DESC, id DESC LIMIT {$perPage} OFFSET " . (($page - 1) * $perPage)); $stmt->execute($params); $logs = $stmt->fetchAll();
$pageTitle = 'Activity Log | ' . APP_NAME; require_once __DIR__ . '/includes/header.php';
?>
<main class="opportunity-page"><div class="container py-5"><div class="opportunity-hero"><div><span class="eyebrow"><i class="bi bi-clock-history"></i> Audit Trail</span><h1>My activity log</h1><p>Your actions are recorded for account security and transparency.</p></div><a class="btn btn-light border" href="<?= e(url('activity_logs.php?' . $query(['export' => 'csv']))) ?>">Export CSV</a></div><section class="opportunity-list-card mt-4"><form class="row g-3 filter-panel" method="get"><div class="col-lg-3"><input class="form-control" name="search" value="<?= e($search) ?>" placeholder="Search activity"></div><div class="col-sm-6 col-lg-2"><select class="form-select" name="module"><option value="">All modules</option><?php foreach ($modules as $item): ?><option value="<?= e($item) ?>" <?= $module === $item ? 'selected' : '' ?>><?= e($item) ?></option><?php endforeach; ?></select></div><div class="col-sm-6 col-lg-2"><select class="form-select" name="action"><option value="">All actions</option><?php foreach ($actions as $item): ?><option value="<?= e($item) ?>" <?= $action === $item ? 'selected' : '' ?>><?= e($item) ?></option><?php endforeach; ?></select></div><div class="col-sm-6 col-lg-2"><input class="form-control" type="date" name="from" value="<?= e($from) ?>"></div><div class="col-sm-6 col-lg-2"><input class="form-control" type="date" name="to" value="<?= e($to) ?>"></div><div class="col-lg-1"><button class="btn btn-outline-primary w-100">Filter</button></div></form><?php if (!$logs): ?><div class="empty-state"><span><i class="bi bi-clock-history"></i></span><h3>No activity found</h3><p>Actions you perform will appear here.</p></div><?php else: ?><div class="table-responsive"><table class="table opportunity-table align-middle"><thead><tr><th>Date</th><th>Module</th><th>Action</th><th>Description</th></tr></thead><tbody><?php foreach ($logs as $log): ?><tr><td class="text-nowrap"><?= e(date('d M Y, h:i A', strtotime($log['created_at']))) ?></td><td><?= e($log['module']) ?></td><td><span class="role-badge"><?= e($log['action']) ?></span></td><td><?= e($log['description']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section><?php if ($total > $perPage): ?><nav class="mt-3"><ul class="pagination justify-content-end mb-0"><?php for ($item = 1; $item <= (int) ceil($total / $perPage); $item++): ?><li class="page-item <?= $item === $page ? 'active' : '' ?>"><a class="page-link" href="<?= e(url('activity_logs.php?' . $query(['page' => $item]))) ?>"><?= $item ?></a></li><?php endfor; ?></ul></nav><?php endif; ?></div></main><?php require_once __DIR__ . '/includes/footer.php'; ?>
