<?php
declare(strict_types=1);
require_once __DIR__ . '/config/app.php';
$pageTitle = APP_NAME . ' | Referral Platform';
require_once __DIR__ . '/includes/header.php';
?>
<main>
    <section class="hero-section">
        <div class="container position-relative">
            <div class="row align-items-center g-5">
                <div class="col-lg-6"><h1 class="hero-title" style="font-size:clamp(3.1rem,5.8vw,5.25rem);font-weight:800;letter-spacing:-.055em;line-height:.98;text-transform:uppercase"><span class="d-block"><?= e(APP_NAME) ?></span></h1><p class="hero-copy" style="font-size:.95rem;line-height:1.6;max-width:650px">Connect businesses, trusted referrers and genuine customers on one powerful platform. Earn rewards, grow your network and support meaningful causes through every successful referral.</p><div class="d-flex flex-wrap gap-3"><a class="btn btn-primary btn-lg" href="<?= e(url('auth/register.php')) ?>">Get Started <i class="bi bi-arrow-right ms-1"></i></a><a class="btn btn-light btn-lg border" href="#how-it-works">Learn More</a></div><div class="hero-trust mt-5"><span><i class="bi bi-shield-check"></i> Transparent process</span><span><i class="bi bi-lightning-charge"></i> Built for simplicity</span></div></div>
                <div class="col-lg-6"><div class="hero-visual"><div class="visual-orbit orbit-one"></div><div class="visual-orbit orbit-two"></div><div class="connection-card card-business"><div class="avatar avatar-blue"><i class="bi bi-buildings"></i></div><div><strong>Business</strong><small>Shares an opportunity</small></div></div><div class="connection-card card-referrer"><div class="avatar avatar-green"><i class="bi bi-person-heart"></i></div><div><strong>Referrer</strong><small>Makes a trusted introduction</small></div></div><div class="connection-card card-reward"><div class="reward-icon"><i class="bi bi-check2"></i></div><div><strong>Success</strong><small>Commission is earned</small></div></div><div class="center-link"><i class="bi bi-link-45deg"></i></div></div></div>
            </div>
        </div>
    </section>
    <section class="section" id="about"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-5"><span class="eyebrow">One platform, shared growth</span><h2>Better introductions. Better outcomes.</h2></div><div class="col-lg-6 offset-lg-1"><p class="lead text-secondary">Refer connects people who know the right customers with businesses ready to serve them. A clear path from introduction to recognition helps every relationship start on trust.</p><div class="mini-stats"><div><strong>3</strong><span>Ways to participate</span></div><div><strong>1</strong><span>Simple, shared platform</span></div><div><strong>100%</strong><span>Focused on genuine connections</span></div></div></div></div></div></section>
    <section class="section section-soft" id="how-it-works"><div class="container"><div class="section-heading text-center"><span class="eyebrow">Simple by design</span><h2>How it works</h2><p>Move from opportunity to outcome with confidence.</p></div><div class="row g-4 process-row"><div class="col-md-4"><article class="process-card"><span>01</span><i class="bi bi-megaphone"></i><h3>Share</h3><p>Businesses introduce opportunities to a network ready to make meaningful connections.</p></article></div><div class="col-md-4"><article class="process-card"><span>02</span><i class="bi bi-people"></i><h3>Connect</h3><p>Referrers bring genuine customers and trusted recommendations to the right business.</p></article></div><div class="col-md-4"><article class="process-card"><span>03</span><i class="bi bi-award"></i><h3>Earn</h3><p>When a referral succeeds, recognition and commission follow through a clear process.</p></article></div></div></div></section>
    <section class="section" id="features"><div class="container"><div class="section-heading"><span class="eyebrow">Built around trust</span><h2>Everything needed to make connections count.</h2></div><div class="row g-4"><div class="col-md-6 col-lg-4"><article class="feature-card"><i class="bi bi-diagram-3"></i><h3>Clear connections</h3><p>Make each introduction intentional, trackable, and easy to understand.</p></article></div><div class="col-md-6 col-lg-4"><article class="feature-card"><i class="bi bi-shield-lock"></i><h3>Secure by default</h3><p>Account security and privacy are foundational to every interaction.</p></article></div><div class="col-md-6 col-lg-4"><article class="feature-card"><i class="bi bi-graph-up-arrow"></i><h3>Growth together</h3><p>Create value for businesses, referrers, and the customers they serve.</p></article></div></div></div></section>
    <section class="section section-soft"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-5"><span class="eyebrow">Why Refer</span><h2>A fairer way to reward the value of a recommendation.</h2></div><div class="col-lg-7"><div class="benefit-list"><div><i class="bi bi-check-circle-fill"></i><span><strong>Focused experience</strong><small>Clear roles for businesses and referrers.</small></span></div><div><i class="bi bi-check-circle-fill"></i><span><strong>Designed for confidence</strong><small>A modern, easy-to-use home for important introductions.</small></span></div><div><i class="bi bi-check-circle-fill"></i><span><strong>Purpose beyond earnings</strong><small>Rewards and charitable giving are part of the platform's future direction.</small></span></div></div></div></div></div></section>
    <section class="section testimonials"><div class="container"><div class="section-heading text-center"><span class="eyebrow">Community voices</span><h2>Made for people who value relationships.</h2></div><div class="row g-4"><div class="col-md-4"><blockquote>“Finally, a straightforward way to turn a trusted introduction into shared value.”<footer>Business owner <span>Early platform community</span></footer></blockquote></div><div class="col-md-4"><blockquote>“The experience feels clear from the start. I know where I fit and what comes next.”<footer>Referrer <span>Early platform community</span></footer></blockquote></div><div class="col-md-4"><blockquote>“A thoughtful product that puts genuine connections before transactions.”<footer>Community partner <span>Early platform community</span></footer></blockquote></div></div></div></section>
    <section class="section" id="faq"><div class="container faq-wrap"><div class="section-heading"><span class="eyebrow">Questions, answered</span><h2>Frequently asked questions</h2></div><div class="accordion" id="faqAccordion"><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" data-bs-toggle="collapse" data-bs-target="#faqOne">Who can join Refer?</button></h3><div id="faqOne" class="accordion-collapse collapse show" data-bs-parent="#faqAccordion"><div class="accordion-body">Businesses and referrers can each create an account with the role that fits them.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#faqTwo">How are successful referrals rewarded?</button></h3><div id="faqTwo" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body">The platform is designed to recognize successful referrals with commissions. Detailed opportunity and payment features are part of future modules.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#faqThree">Is my account information protected?</button></h3><div id="faqThree" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body">Passwords are securely hashed and authentication uses protected sessions and prepared database queries.</div></div></div></div></div></section>
    <section class="cta-section"><div class="container"><div><span class="eyebrow text-white bg-white bg-opacity-25">Start today</span><h2>Be part of a better referral economy.</h2><p>Create your account in a few minutes and choose how you want to participate.</p></div><a class="btn btn-light btn-lg" href="<?= e(url('auth/register.php')) ?>">Create an account <i class="bi bi-arrow-right ms-1"></i></a></div></section>
</main>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
