<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../includes/referral_opportunities.php';
require_once __DIR__ . '/../includes/customer_referrals.php';

require_login('REFERRER');
$search = trim((string) ($_GET['search'] ?? ''));
$category = trim((string) ($_GET['category'] ?? ''));
$location = trim((string) ($_GET['location'] ?? ''));
$product = trim((string) ($_GET['product'] ?? ''));
$sort = (string) ($_GET['sort'] ?? 'latest');
$where = ["o.status = 'Active'", 'o.valid_until >= CURDATE()']; $params = [];
if ($search !== '') { $where[] = '(o.title LIKE ? OR COALESCE(b.business_name, u.full_name) LIKE ? OR o.service_location LIKE ?)'; $term = '%' . $search . '%'; array_push($params, $term, $term, $term); }
if (in_array($category, REFERRAL_OPPORTUNITY_CATEGORIES, true)) { $where[] = 'o.category = ?'; $params[] = $category; } else $category = '';
if ($location !== '') { $where[] = 'o.service_location LIKE ?'; $params[] = '%' . $location . '%'; }
if ($product !== '') { $where[] = 'EXISTS (SELECT 1 FROM opportunity_products filter_product WHERE filter_product.opportunity_id = o.id AND filter_product.product_name = ?)'; $params[] = $product; }
$order = match ($sort) { 'commission' => 'starting_commission DESC, o.created_at DESC', 'expiry' => 'o.valid_until ASC, o.created_at DESC', default => 'o.created_at DESC' };
if (!in_array($sort, ['latest', 'commission', 'expiry'], true)) $sort = 'latest';
$statement = db()->prepare('SELECT o.*, COALESCE(b.business_name, u.full_name) AS business_name, b.logo, b.city AS business_city, COALESCE(product_stats.product_count, 0) AS product_count, COALESCE(product_stats.starting_commission, 0) AS starting_commission FROM referral_opportunities o JOIN users u ON u.id = o.business_id LEFT JOIN business_profiles b ON b.user_id = o.business_id LEFT JOIN (SELECT opportunity_id, COUNT(*) AS product_count, MIN(commission_percentage) AS starting_commission FROM opportunity_products GROUP BY opportunity_id) product_stats ON product_stats.opportunity_id = o.id WHERE ' . implode(' AND ', $where) . ' ORDER BY ' . $order);
$statement->execute($params); $opportunities = $statement->fetchAll();
$productOptions = db()->query("SELECT DISTINCT product_name FROM opportunity_products ORDER BY product_name")->fetchAll(PDO::FETCH_COLUMN);
$pageTitle = 'Browse opportunities | ' . APP_NAME; require_once __DIR__ . '/../includes/header.php';
?>
<main class="opportunity-page"><div class="container py-5"><div class="opportunity-hero"><div><span class="eyebrow"><i class="bi bi-search"></i> Referrer workspace</span><h1>Browse opportunities</h1><p>Find active opportunities and introduce customers who are a great fit.</p></div><a class="btn btn-light border" href="<?= e(url('referrer/referrals.php')) ?>"><i class="bi bi-people"></i> My referrals</a></div>
<section class="opportunity-list-card mt-4"><form class="opportunity-filters" method="get"><div class="row g-3"><div class="col-lg-4"><input class="form-control" name="search" value="<?= e($search) ?>" placeholder="Search campaign title" data-instant-search></div><div class="col-sm-6 col-lg-2"><select class="form-select" name="category"><option value="">All categories</option><?php foreach (REFERRAL_OPPORTUNITY_CATEGORIES as $item): ?><option value="<?= e($item) ?>" <?= $category === $item ? 'selected' : '' ?>><?= e($item) ?></option><?php endforeach; ?></select></div><div class="col-sm-6 col-lg-2"><select class="form-select" name="product"><option value="">All products</option><?php foreach ($productOptions as $item): ?><option <?= $product === $item ? 'selected' : '' ?>><?= e($item) ?></option><?php endforeach; ?></select></div><div class="col-sm-6 col-lg-2"><input class="form-control" name="location" value="<?= e($location) ?>" placeholder="Location"></div><div class="col-sm-6 col-lg-2"><select class="form-select" name="sort"><option value="latest" <?= $sort === 'latest' ? 'selected' : '' ?>>Latest</option><option value="commission" <?= $sort === 'commission' ? 'selected' : '' ?>>Highest commission</option><option value="expiry" <?= $sort === 'expiry' ? 'selected' : '' ?>>Nearest expiry</option></select></div><div class="col-12 d-flex gap-2 justify-content-end"><button class="btn btn-outline-primary">Apply filters</button><a class="btn btn-light border" href="<?= e(url('referrer/opportunities.php')) ?>">Clear filters</a></div></div></form>
<?php if (!$opportunities): ?><div class="empty-state"><span><i class="bi bi-inbox"></i></span><h3>No active opportunities found</h3><p>Try changing your search or filters.</p></div><?php else: ?><div class="row g-4 mt-1"><?php foreach ($opportunities as $opportunity): ?><div class="col-md-6 col-xl-4"><article class="detail-card h-100 d-flex flex-column"><div class="d-flex align-items-center gap-2 mb-3"><?php if ($opportunity['logo']): ?><img src="<?= e(url($opportunity['logo'])) ?>" alt="" class="rounded" style="height:38px;width:38px;object-fit:cover"><?php else: ?><span class="brand-mark"><i class="bi bi-building"></i></span><?php endif; ?><div><strong class="d-block text-dark"><?= e($opportunity['business_name']) ?></strong><small><?= e($opportunity['business_city'] ?: $opportunity['service_location']) ?></small></div></div><span class="eyebrow mb-2"><?= e($opportunity['category']) ?></span><h2 class="fs-5"><?= e($opportunity['title']) ?></h2><p class="small flex-grow-1"><?= e(mb_strimwidth($opportunity['description'], 0, 150, '…')) ?></p><dl class="detail-list mb-3"><div><dt>Campaign status</dt><dd><span class="role-badge"><?= e($opportunity['status']) ?></span></dd></div><div><dt>Products / services</dt><dd><?= (int) $opportunity['product_count'] ?></dd></div><div><dt>Starting commission</dt><dd><?= e($opportunity['starting_commission']) ?>%</dd></div><div><dt>Expiry date</dt><dd><?= e(date('d M Y', strtotime($opportunity['valid_until']))) ?></dd></div></dl><div class="d-flex gap-2"><a class="btn btn-light border flex-fill" href="<?= e(url('referrer/opportunity.php?id=' . $opportunity['id'])) ?>">View details</a><a class="btn btn-primary flex-fill" href="<?= e(url('referrer/referral_form.php?id=' . $opportunity['id'])) ?>">Submit referral</a></div></article></div><?php endforeach; ?></div><?php endif; ?></section></div></main>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
