USE referral_platform;

CREATE TABLE IF NOT EXISTS referrer_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  gender ENUM('Male', 'Female', 'Non-binary', 'Prefer not to say') NOT NULL,
  mobile_number VARCHAR(25) NOT NULL,
  alternate_mobile VARCHAR(25) NULL,
  email VARCHAR(150) NOT NULL,
  profile_photo VARCHAR(255) NULL,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  pincode VARCHAR(20) NOT NULL,
  occupation VARCHAR(150) NOT NULL,
  service_categories JSON NOT NULL,
  experience_level ENUM('Fresher', '1–3 Years', '3–5 Years', '5+ Years') NOT NULL,
  bio TEXT NOT NULL,
  government_id_type ENUM('Aadhaar', 'PAN', 'Driving Licence', 'Passport', 'Voter ID') NOT NULL,
  government_id_number VARCHAR(100) NOT NULL,
  government_id_document VARCHAR(255) NULL,
  bank_account_name VARCHAR(150) NOT NULL,
  bank_account_number VARCHAR(34) NOT NULL,
  ifsc_code VARCHAR(11) NOT NULL,
  upi_id VARCHAR(150) NULL,
  verification_status ENUM('Pending', 'Verified', 'Rejected') NOT NULL DEFAULT 'Pending',
  is_profile_completed TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY referrer_profiles_user_unique (user_id),
  KEY referrer_profiles_status_index (verification_status),
  CONSTRAINT referrer_profiles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
