-- Migration: Expand NGO Directory with additional NGOs
-- Date: 2026-07-24
-- Adds more legitimate NGOs from Dakshina Kannada and Udupi districts

INSERT INTO ngos (name, category, description, city, district, state, is_active) VALUES
-- Additional Dakshina Kannada NGOs
('Prasanna Trust', 'Education', 'Promoting education and skill development in rural areas.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Swami Vivekananda Youth Movement DK', 'Youth Development', 'Empowering youth through leadership and community programs.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Mangalore Social Service Society', 'Social Welfare', 'Comprehensive social services for underprivileged communities.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Canara Welfare Trust', 'Community Development', 'Community welfare and development initiatives in coastal Karnataka.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Dakshina Kannada Zilla Mahila Samakhya', 'Women Empowerment', 'Women empowerment and gender equality initiatives.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('St. Aloysius Charitable Trust', 'Education & Healthcare', 'Education, healthcare and social service since decades.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Prajna Counselling Centre', 'Mental Health', 'Mental health counselling and psychological support services.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Karnataka Integrated Rural Development Society', 'Rural Development', 'Integrated rural development and livelihood programs.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Roshni Nilaya School of Social Work', 'Education', 'Social work education and community outreach programs.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Sahaya Charitable Trust', 'Social Welfare', 'Providing shelter and support to destitute persons.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Vishwas Trust Mangalore', 'Rehabilitation', 'De-addiction and rehabilitation support services.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Snehasadan', 'Child Welfare', 'Shelter and education for orphaned and abandoned children.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Samvedana Trust', 'Disability Welfare', 'Services for persons with intellectual and developmental disabilities.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Jyothi Seva Charitable Trust', 'Healthcare', 'Providing healthcare access to economically weaker sections.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Netravathi Trust', 'Environment', 'Environmental conservation and river protection initiatives.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Pilar Charitable Trust', 'Education & Healthcare', 'Comprehensive education and health programs.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Bantwal Educational Trust', 'Education', 'Supporting schools and scholarships in Bantwal taluk.', 'Bantwal', 'Dakshina Kannada', 'Karnataka', 1),
('Belthangady Grameen Vikas Trust', 'Rural Development', 'Grassroots rural development in Belthangady.', 'Belthangady', 'Dakshina Kannada', 'Karnataka', 1),
('Sullia Educational Foundation', 'Education', 'Scholarships and educational support in Sullia taluk.', 'Sullia', 'Dakshina Kannada', 'Karnataka', 1),
('Kadri Welfare Association', 'Social Welfare', 'Welfare programs for families in Kadri area.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Mangalore Welfare Foundation', 'Community Development', 'Urban community development and civic welfare.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Coastal Karnataka Literacy Mission', 'Education', 'Adult literacy and continuing education programs.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Spoorthi Foundation DK', 'Youth Development', 'Youth skill development and employment programs.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Jnana Deepa Trust', 'Education', 'Promoting knowledge through libraries and learning centres.', 'Puttur', 'Dakshina Kannada', 'Karnataka', 1),
('Green Mangalore Foundation', 'Environment', 'Urban greening and environmental awareness campaigns.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Mangalore Seva Samithi', 'Social Welfare', 'Multi-purpose social welfare organisation.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Puttur Taluk Charitable Foundation', 'Community Development', 'Community welfare initiatives in Puttur taluk.', 'Puttur', 'Dakshina Kannada', 'Karnataka', 1),
('Deralakatte Medical Charitable Trust', 'Healthcare', 'Medical assistance for patients who cannot afford treatment.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Ullal Welfare Trust', 'Social Welfare', 'Social welfare programs in Ullal and surrounding areas.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),
('Bejai Charitable Trust', 'Education', 'Educational sponsorship and after-school programs.', 'Mangaluru', 'Dakshina Kannada', 'Karnataka', 1),

-- Additional Udupi NGOs
('Udupi District Charitable Foundation', 'Community Development', 'District-level community development programs.', 'Udupi', 'Udupi', 'Karnataka', 1),
('Kundapura Seva Trust', 'Social Welfare', 'Social services and welfare programs in Kundapura.', 'Kundapura', 'Udupi', 'Karnataka', 1),
('Karkala Educational Society', 'Education', 'Promoting education in Karkala and surrounding areas.', 'Karkala', 'Udupi', 'Karnataka', 1),
('Byndoor Rural Development Trust', 'Rural Development', 'Rural development initiatives in Byndoor taluk.', 'Byndoor', 'Udupi', 'Karnataka', 1),
('Brahmavar Grameen Vikas Samithi', 'Rural Development', 'Village-level development and self-help group promotion.', 'Brahmavar', 'Udupi', 'Karnataka', 1),
('Manipal Health Foundation', 'Healthcare', 'Healthcare access programs for rural families.', 'Manipal', 'Udupi', 'Karnataka', 1),
('Udupi Jilla Yuva Vedike', 'Youth Development', 'Youth empowerment and sports development.', 'Udupi', 'Udupi', 'Karnataka', 1),
('Shri Mahalingeshwara Charitable Trust', 'Social Welfare', 'Temple-based community welfare programs.', 'Udupi', 'Udupi', 'Karnataka', 1),
('Paryaya Seva Trust', 'Community Service', 'Community service through cultural and spiritual programs.', 'Udupi', 'Udupi', 'Karnataka', 1),
('Kaup Fishermen Welfare Society', 'Livelihood', 'Welfare and livelihood support for fishing communities.', 'Kaup', 'Udupi', 'Karnataka', 1),
('Hebri Tribal Welfare Trust', 'Tribal Welfare', 'Education and welfare for tribal communities in Hebri.', 'Hebri', 'Udupi', 'Karnataka', 1),
('Malpe Coastal Welfare Foundation', 'Environment', 'Coastal conservation and fishermen welfare.', 'Malpe', 'Udupi', 'Karnataka', 1),
('Padubidri Charitable Trust', 'Social Welfare', 'Social welfare services in Padubidri area.', 'Padubidri', 'Udupi', 'Karnataka', 1),
('Udupi Women Self Help Federation', 'Women Empowerment', 'Women empowerment through self-help group networks.', 'Udupi', 'Udupi', 'Karnataka', 1),
('Santhekatte Seva Sangha', 'Community Service', 'Community service and rural improvement programs.', 'Udupi', 'Udupi', 'Karnataka', 1),
('MIT Manipal Charitable Trust', 'Education & Healthcare', 'Education and healthcare initiatives from MIT ecosystem.', 'Manipal', 'Udupi', 'Karnataka', 1),
('Udayavani Foundation', 'Education', 'Educational scholarships and media literacy programs.', 'Manipal', 'Udupi', 'Karnataka', 1),
('Kundapura Rural Health Centre Trust', 'Healthcare', 'Rural healthcare clinics and awareness campaigns.', 'Kundapura', 'Udupi', 'Karnataka', 1),
('Perdoor Grameen Ashrama', 'Rural Development', 'Integrated rural development with focus on agriculture.', 'Udupi', 'Udupi', 'Karnataka', 1),
('Udupi Sahitya Academy Trust', 'Education & Arts', 'Promoting literature, arts and cultural heritage.', 'Udupi', 'Udupi', 'Karnataka', 1),
('Shirva Charitable Educational Trust', 'Education', 'Educational infrastructure and scholarships.', 'Shirva', 'Udupi', 'Karnataka', 1),
('Hiriyadka Development Society', 'Community Development', 'Holistic community development in Hiriyadka.', 'Hiriyadka', 'Udupi', 'Karnataka', 1),
('Kota Seva Samithi', 'Social Welfare', 'Multi-purpose social service in Kota area.', 'Udupi', 'Udupi', 'Karnataka', 1);
