<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/app.php';
$user = require_login($requiredRole);
$pageTitle = $dashboardTitle . ' | ' . APP_NAME;
require_once __DIR__ . '/header.php';
?>
<main class="dashboard-page"><div class="container py-5"><div class="dashboard-welcome"><div><span class="eyebrow"><?= e(role_label($user['role'])) ?> workspace</span><h1><?= e($dashboardTitle) ?></h1><p>Welcome back, <?= e($user['full_name']) ?>. Your platform workspace is ready.</p></div><div class="welcome-icon"><i class="bi <?= e($dashboardIcon) ?>"></i></div></div><div class="row g-4 mt-1"><div class="col-sm-6 col-lg-3"><div class="stat-card"><i class="bi bi-briefcase"></i><span>Active opportunities</span><strong>--</strong><small>Available in a future module</small></div></div><div class="col-sm-6 col-lg-3"><div class="stat-card"><i class="bi bi-people"></i><span>Connections</span><strong>--</strong><small>Available in a future module</small></div></div><div class="col-sm-6 col-lg-3"><div class="stat-card"><i class="bi bi-cash-coin"></i><span>Commission</span><strong>--</strong><small>Available in a future module</small></div></div><div class="col-sm-6 col-lg-3"><div class="stat-card"><i class="bi bi-bar-chart"></i><span>Activity</span><strong>--</strong><small>Available in a future module</small></div></div></div><div class="row g-4 mt-1"><div class="col-lg-7"><section class="dashboard-panel"><div class="panel-heading"><div><h2>Recent activity</h2><p>Your activity will appear here as you use the platform.</p></div><i class="bi bi-clock-history"></i></div><div class="empty-state"><span><i class="bi bi-inbox"></i></span><h3>No activity yet</h3><p>New referral activity will be visible here in a future module.</p></div></section></div><div class="col-lg-5"><section class="dashboard-panel user-panel"><div class="panel-heading"><div><h2>Your account</h2><p>Current signed-in details.</p></div><i class="bi bi-person-vcard"></i></div><dl><div><dt>Full name</dt><dd><?= e($user['full_name']) ?></dd></div><div><dt>Email</dt><dd><?= e($user['email']) ?></dd></div><div><dt>Phone</dt><dd><?= e($user['phone']) ?></dd></div><div><dt>Role</dt><dd><span class="role-badge"><?= e(role_label($user['role'])) ?></span></dd></div></dl></section></div></div></div></main>
<?php require_once __DIR__ . '/footer.php'; ?>
